Desktop Version
MoRaad97/portfolio-website-Microverse-project pull request #5
Opened 2022-04-27 17:02 UTC by MoRaad97

2022-04-28 22:40 UTC, youmari requested changes
Hi @MoRaad97 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [x] Doesn't have a Descriptive short summary 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-29 00:13 UTC, koomekevo requested changes
Hi @MoRaad97, 

<img src="https://media3.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
:heavy_check_mark: You have implemented the media queries correctly.
:heavy_check_mark: Your README and Pull Request are descriptive.
:heavy_check_mark: Your project has no linter errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 00:13 UTC, koomekevo commented on index.html
>            <h1>Hey There. I’m Mohammed</h1>
@MoRaad97 Kindly add spacing between the `Hey there I am Mohammed` sentence and `I am a software developer` sentence as shown in the below screenshot as per the Figma design.

![mohaheytherecorrect](https://user-images.githubusercontent.com/87413774/165865134-a2488e46-26da-45f5-825f-85ac30e220b3.png) 

The below screenshot is your design 

![mohaheytherewrongedited](https://user-images.githubusercontent.com/87413774/165865392-90955893-d209-4643-8478-4227a2f3c393.png)

2022-04-29 00:13 UTC, koomekevo commented on index.html
>            <h1>My Recent Work</h1>
@MoRaad97 Kindly modify the `My recent work` section according to the content of the Figma template. Four cards do not resemble the content of the Figma template which I have circled in the below screenshot. 

![moharecentworkswrongedited](https://user-images.githubusercontent.com/87413774/165866605-bab34faa-a957-4df4-992f-b58c9a8033d2.png)

Below is the correct screenshot showing the correct content of the `My recent works` section

![moharecentworkscorrect](https://user-images.githubusercontent.com/87413774/165866704-4b5c382e-44cf-46f5-aff7-b88551151b47.png)

2022-04-29 01:11 UTC, danielufeli approved these changes
Hi @MoRaad97, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Clean Design ✔️
- Good use of Github flow ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 01:13 UTC, merged